services:
  mysql:
    image: mysql:8.0
    container_name: gestion-dechets-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "gestion_dechets_db"
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql-mode=
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD/script_mysql_complet.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  mysql_data:
